### ISSUE TITLE
Some illegal encodings not detected

### ISSUE THREAD

**Issue by PeterRugg** [csail-csg/riscy-OOO#10]
The `JALR` and branch instructions have redundant encodings in their `funct3` fields that are illegal. Based on my reading of the spec: for `JALR`, only `3'b000` is legal, and for branches, `3'b010` and `3'b011` are illegal. These cases aren't addressed in decode: https://github.com/csail-csg/riscy-OOO/blob/4d84c7c6fd84ae351fceba8a67232022e71785e9/procs/lib/Decode.bsv#L370-L395

For `JALR`, this leads to it having 8 encodings that all behave identically. For branches, presumably the case gives an undefined result, which hopefully defaults to one of the other legal cases.

This came up as I was fuzzing and wasn't getting a trap on `0x0000a267`: a `JALR` but with `3'b010` instead of `3'b000` in the `funct3` field.

I'd be happy to make a PR to fix this if I've identified the issue correctly.

**Comment by threonorm** [comment]
Thanks for finding this bug!  
Agreed, this look like a bug. I will try to trigger the bug on the machine early next week, but a priori, it is a bug. Moreover, you can see at line 187 of the same file that there were some suspicions that we were not proper handling of illegal instructions. I believe you identified the issue correctly.

I am curious, how did you fuzz? Did you fuzz the decoder in isolation? Or did you do riscv-level software fuzzing, running arbitrary generated full riscv programs on the processor? 

Note: I believe this bug will also exist in this repo https://github.com/bluespec/Toooba/  so if you can make a PR on both repo it would be great (they are not kept in sync).

**Comment by PeterRugg** [comment]
Great, thanks for the quick response. We're fuzzing using TestRIG (https://github.com/CTSRD-CHERI/TestRIG), so it's pretty much software-level. I didn't intend to sweep the whole instruction space, just the 16-bit compressed encodings, but forgot to exclude the 32-bit instructions that happen to have 16 bits of zeros. I am indeed working with Toooba, so will put in the PR there too.
