### ISSUE TITLE
use of make target 'hw/mkTop.bit'

### ISSUE THREAD

**Issue by yswntht** [csail-csg/riscy-OOO#4]
Hi,

I just want to confirm that make target `hw/mkTop.bit` is a part of **synthesis flow** only for fpga boards (eg. zedboard, vc707 etc) and not for **awsf1**, right?.

Thanks!

**Comment by sizhuo-zhang** [comment]
You are right. For awsf1, we generate only vivado checkpoint files, and the checkpoint after routing will be uploaded to AWS to generate the final FPGA bitstream. Programming the AWS FPGA needs only the AGFI ID. For vc707 etc., we can generate the final bitstream locally.
