### ISSUE TITLE
Unnecessary TLB flush on write to SATP?

### ISSUE THREAD

**Issue by PeterRugg** [csail-csg/riscy-OOO#8]
The `makeSystemConsistent` call in the CommitStage:https://github.com/csail-csg/riscy-OOO/blob/4d84c7c6fd84ae351fceba8a67232022e71785e9/procs/RV64G_OOO/CommitStage.bsv#L504 flushes all TLBs on any write to SATP. This seems overzealous, as the ASID of entries is also saved in the TLB, so there should be no risk of incorrect aliasing. From the spec: "Changes in the satp register do not necessarily flush any such translation caches." If the processor is recycling an ASID, then the RISC-V spec requires an sfence.VMA.

This may prevent TLB entries sticking around across context switches if working sets are small, hurting performance, and will also require two consecutive flushes in the common case of changing SATP and calling sfence.VMA in short succession.

**Comment by sizhuo-zhang** [comment]
Thanks for pointing this out. We might not have implemented ASID (it is 0-bit wide), so we just flush TLB on writes to SATP. At the time of development, we were trying to be conservative about system instructions as you have noticed. This repo is not actively maintained. This processor has been taken over by Bluespec Inc., and is maintained in [https://github.com/bluespec/Toooba](https://github.com/bluespec/Toooba). You are welcome to submit comments and pull requests there. Thanks!
